language: python

dist: xenial  # required for Python >= 3.7

branches:
  only:
    - master

cache: pip

python:
  #- "3.5"
  #- "3.6"
  - "3.7"

install:
  - make

script:
  - make test-readme
  - make ci

#deploy:
#  provider: releases
#  api_key:
#    secure: *
#  file:
#    - dist/*.whl
#    - dist/*.tar.gz
#  file_glob: true
#  on:
#    repo: syspass/syspass-api-client-python
#    tags: true
#  skip_cleanup: true